### ISSUE TITLE
using_pycmc.ipynb has WMTS url that throws a 500

### ISSUE THREAD

**Issue by philvarner** [MAAP-Project/maap-documentation#107]
The "Visualizing Web Map Tile Service (WMTS) Layers" example uses the url:

```
https://api.maap-project.org/api/wmts/GetCapabilities?granule_ur=SC:AFLVIS2.001:138348905
```

which returns a 500 status code.

The issue is likely that CMR requires a short_name and version to query by granule_ur, and this request doesn't have that. 

This request does work:

`https://api.ops.maap-project.org/api/wmts/GetCapabilities?short_name=AFLVIS2&version=001&granule_ur=SC:AFLVIS2.001:138348905`

**Comment by abarciauskas-bgse** [comment]
closing as stale
