### ISSUE TITLE
TOC incorrect levels

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/maap-documentation#127]
With the latest PR #126 something went wrong with the table of contents on the navigation. It's listing the new HLS and GEDI tutorials instead of nesting them under a new Tutorials label.

![image](https://user-images.githubusercontent.com/306179/194416928-887aa965-fbfc-4713-b3ce-a5969960587f.png)

**Comment by sumantjha** [comment]
> With the latest PR #126 something went wrong with the table of contents on the navigation. It's listing the new HLS and GEDI tutorials instead of nesting them under a new Tutorials label.
> 
> ![image](https://user-images.githubusercontent.com/306179/194416928-887aa965-fbfc-4713-b3ce-a5969960587f.png)

@wildintellect @chuckwondo Chuck mentioned in review of #126 to take out the first 3 lines from the tutorial.rst
Just verified that taking that out resulted in the subheadings (notebook names and subheadings) being displayed in the index file. I have replaced it back and ran sphinx again. I do not see those subheadings that Alex mentioned.

**Comment by sumantjha** [comment]
![Screen Shot 2022-10-06 at 3 48 24 PM](https://user-images.githubusercontent.com/24756569/194432396-eaa515a8-2abc-46a1-8253-96e3eeab7bc8.png)
