### ISSUE TITLE
GEDI L2B Notebook Syntax error 

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/maap-documentation#128]
Something went wrong with the copy of the GEDI L2B notebook. Instead of showing the Png it's showing the binary.
Check the image reference in the markdown. cc: @nmt28

![image](https://user-images.githubusercontent.com/306179/194417542-fd0eb5c1-9749-40a5-91bb-d18359fa415d.png)

**Comment by sumantjha** [comment]
Changed the image path and updated the notebook.
