### ISSUE TITLE
Document different discovery and access methods for MAAP catalogs

### ISSUE THREAD

**Issue by abarciauskas-bgse** [MAAP-Project/maap-documentation#142]
Add the following documentation to https://docs.maap-project.org:

## How to discover data

There are 2 "official" MAAP catalogs:

* https://cmr.earthdata.nasa.gov
* https://stac.maap-project.org

At this time, we also have cmr.maap-project.org but this catalog should be deprecated this year so users are encouraged to request collections that are available in cmr.maap-project.org to be made discoverable in stac.maap-project.

[... documentation about how to discover data from each ...]

### cmr.earthdata.nasa.gov

1. LPDAAC - all accessible to MAAP users through role-based bucket policy
2. ORNL DAAC - federated access token
3. All other cloud data - requires EDL credentials to obtain S3 credentials for direct access
4. All other on-prem data - requires EDL credentials (is the only method document using `~/.netrc`?)

### stac.maap-project.org

All datasets published in stac.maap-project.org should be accessible through role-based bucket policy for MAAP users or publicly available

Currently in the STAC catalog there is data from
1. Data in nasa-maap-data-store - accessible to all MAAP users through role-based bucket policy or publicly available (depending on the collection, document which collections)
2. Data from ESA's data servers - publicly available

Coming soon, there may be 
1. Data in maap-user-shared-data - accessible to all MAAP users through role-based bucket policy (Open question: should this be publicly available)
2. Coming soon: Data from AWS Public Datasets

**Comment by wildintellect** [comment]
This doesn't capture the nuance that for each DAAC, some data is in EarthDataCloud (s3 accessible) and some data is OnPrem. OnPrem data will still require federated EDL, or direct EDL usage.

Who can confirm that only LPDAAC and ORNLDAAC work with federated tokens?

**Comment by abarciauskas-bgse** [comment]
Good point about on-prem vs Earthdata Cloud - I've added this differentiation in the outline.

I think whomever works on this ticket should be able to `confirm that only LPDAAC and ORNLDAAC work with federated tokens` in practice but perhaps @gchang can confirm the understanding that the federated access token works for LPDAAC (although a token for LPDAAC now seems obsolete) and ORNL DAAC

**Comment by gchang** [comment]
Is there a particular LPDAAC URL/dataset/granule to check? @bsatoriu can do a quick test for that. I think he's already done testing on ORNL as that was the first DAAC we tested.

**Comment by abarciauskas-bgse** [comment]
Actually I was under the assumption that the federated access token was only meant to work for LP DAAC and ORNL DAAC and that it doesn't work for other DAACs.

@wildintellect the federated token is required for on-prem data where it works (LP DAAC and ORNL DAAK AFAIK) _but_ the user could still use EDL credentials if they have them _but_ the outline distinguishes between those 2 DAACs and all the other DAACs, which I don't believe the federated access token works for (on-prem or Earthdata cloud)

... This is all making it more clear both that we need this documentation and that we need a simpler solution.

**Comment by bsatoriu** [comment]
@abarciauskas-bgse federated access tokens are meant to work for all DAACs, but has not been exhaustively tested. This doc provides working examples for ORNL and ASF: https://docs.maap-project.org/en/latest/access/accessing_external_data.html

**Comment by abarciauskas-bgse** [comment]
oh that's great!

**Comment by abarciauskas-bgse** [comment]
Thinking a bit more about documentation:

NASA's operational CMR:
* anything that is in NASA's operational CMR should be discovered via EDSC or maap-py search
* anything that is in NASA's operational CMR should be accessed via maap-py so that the federated access token can be used. Users can also access data from LPDAAC (and possible other DAACs in the future) without maap-py since the workspace should have access via a role-based bucket policy on the LPDAAC cloud bucket

MAAP STAC:
* assumption: nothing in MAAP STAC is _also_ discoverable via NASA's operational CMR
* discovered via pystac-client or maap-stac-browser
* accessed via public access or role-based bucket policy access

**Comment by abarciauskas-bgse** [comment]
PR is open https://github.com/MAAP-Project/maap-documentation/pull/162

but I still want to:
- [ ] run through AI editor or some such to improve readability
- [ ] Get feedback from users
- [ ] Fix relative links to pages
- [ ] Address changes in other search pages.

**Comment by abarciauskas-bgse** [comment]
- [ ] Create new tickets for changing the other pages to ensure they don't rely on cmr.maap-project.org (1 ticket for each section)
