### ISSUE TITLE
Unclear workspace naming/description

### ISSUE THREAD

**Issue by emileten** [MAAP-Project/maap-documentation#163]
@wildintellect, creating an issue based on your comment : https://github.com/MAAP-Project/maap-documentation/pull/159#discussion_r1150829689. Quoting : 

> We should probably raise a ticket that it's unclear that he Basic Stable is python and that all other workspaces also include python as part of conda environments. 

Workspace naming isn't happening here but I am filing this here for now. 

Could you elaborate a little bit on this ? By 'unclear', did you mean that the _**description**_ of the workspace (that shows up e.g. when one creates a new workspace instance in the ADE, [and that is coded up here](https://github.com/MAAP-Project/maap-workspaces/blob/develop/devfiles/vanilla/devfile/meta.yaml)) is unclear, as in, it doesn't reflect the differences across workspaces in terms of what libraries are installed ?

**Comment by wildintellect** [comment]
@emileten right this wasn't an issue with your notebook, it's an issue with the Platform. @gchang should we move this ticket to Zenhub? We're suggesting that Basic Stable include the word `Python` in it's name, or somehow indicate why a user would pick it.

**Comment by rtapella** [comment]
In v4.0.0, workspaces have been renamed. Closing

- Basic Stable is now Python (default) (conda env: "python")
- Also the R workspace now includes both R and python by default
