### ISSUE TITLE
Clean Up MAAP Documenation inactive Branches

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/maap-documentation#169]
There are a lot of branches on this project, and the majority of them are Stale (haven't been worked on in a long time).

Acceptance Criteria:
- [x] Close any stale branch that has 0 commits ahead of `Develop`
- [x] Identify and close any other branches that are no longer active or relevant
- [x] Fast track all open PR reviews to get them merged ASAP

**Comment by wildintellect** [comment]
- I closed everything more than 1 year old. 
- Closed any branch that is already merged, and has 0 new commits.

Some of them may old info for future work, but we can always look them up in the history. 
The bigger challenge is to check the remaining `Stale` branches to see if they are still active. @abarciauskas-bgse you own all of them (5) https://github.com/MAAP-Project/maap-documentation/branches/stale can you please decide which can be closed?

**Comment by abarciauskas-bgse** [comment]
* ab/stac-search appears to be mostly covered by new stac documentation, although it does include more pystac client examples

**Comment by abarciauskas-bgse** [comment]
* ab/stac-search and ab/searc-and-visualize appear to be mostly covered by new or existing  documentation, although it does include more pystac client examples , so I have deleted those


* https://github.com/MAAP-Project/maap-documentation/tree/ab/started-tutorials-for-stac includes a tutorial for Afrisar AGB maps - https://github.com/MAAP-Project/maap-documentation/commit/8ad7380b7ed4e6ead38aea1368aeaf03b76a99ec - should we include this type of documentation? It's not in a finished state obviously, so would take some more work.
* https://github.com/MAAP-Project/maap-documentation/compare/develop...ab/add_cw_query_notebooks includes CW for CMR logs - perhaps I should share these with the CMR team in slack and then we can delete this one
* https://github.com/MAAP-Project/maap-documentation/compare/develop...ab/add-dynamic-viz-documentation this I think actually creates a panel dashboard, as part of a flex week project https://github.com/developmentseed/earthdata-team/issues/112. I don't want to lose this work so perhaps I should move it to maap-documentation-examples?

**Comment by wildintellect** [comment]
> I don't want to lose this work so perhaps I should move it to maap-documentation-examples?
:100:

**Comment by abarciauskas-bgse** [comment]
I've cleaned up the branches you identified as stale @wildintellect I think we can close this. I still have ab/add-icesat2-mosaic but we may want to use that for the new version of the ICESat-2 Boreal product?
