### ISSUE TITLE
Improve Custom Env instructions - ipykernel

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/maap-documentation#180]
https://docs.maap-project.org/en/latest/system_reference_guide/custom-environments.html#Custom-environments

The current instructions seem so be confusing users (as reported on [slack](https://esa-nasa-maap.slack.com/archives/C01308ZHELF/p1682525204396679?thread_ts=1681321078.902189&cid=C01308ZHELF))

It's also not clear that installing [ipkernel](https://docs.maap-project.org/en/latest/system_reference_guide/custom-environments.html#Using-custom-environments-in-jupyter-notebooks) from outside the conda env works as expected.
Nor is it clear that this is specifically for python. If you want to use R or another language it's a different kernel package.

Steps known to work:
1. Create conda env
2. install ipykernel or correct kernel for language (can be done at env create time with package declarations)
3. Activate the kernel (in terminal) at least once
4. Note that these envs don't survive restarts of workspaces (more boldly with a Caution/Warning tag)

`mamba env create -f env.yml --prefix /projects/env` might lead to some issues, because the conda files might survive reboot but that doesn't mean conda will know about them. We should look at how AWS Sagemaker Studio Lab manages to do this.

**Comment by freitagb** [comment]
@sdradsb to lead this effort @emileten to consult.

**Comment by emileten** [comment]
https://github.com/MAAP-Project/maap-documentation/pull/178#discussion_r1181772131

**Comment by rtapella** [comment]
The original PR this refers to has been moved to this branch:
https://github.com/MAAP-Project/maap-documentation/tree/Getting-Started-pr-branch

https://docs.maap-project.org/en/getting-started-pr-branch/

**Comment by emileten** [comment]
FYI I fixed the small duplicate images issue in that custom env page that Rob had caught : https://github.com/MAAP-Project/maap-documentation/pull/184/commits/4214323c5976a5489fa57b04fae5474281af102f1.

Let me know if you need more background about this ticket @sdradsb.

**Comment by emileten** [comment]
Updated link (docs in development) https://docs.maap-project.org/en/getting-started-pr-branch/system_reference_guide/custom-environments.html

@sdradsb. From your slack message: 

> I created an environment using prefix=‘/projects/env’ and the environment existed even after the workspace restart. When reactivating that environment I used conda activate  /projects/env and it worked too.

Let's assume then that we shouldn't be too concerned about (quoting alex's description)

> mamba env create -f env.yml --prefix /projects/env might lead to some issues, because the conda files might survive reboot but that doesn't mean conda will know about them.

However, we still have issues regarding registering a kernel and seeing it as available in a notebook selection. These are the issues that remain :

1. It's not clear enough in the docs I wrote that `ipykernel` must be installed in any given `conda` environment to be used in a kernel one wants to register. It should be made clearer. 
2. There is a known delay between kernel registration and its availability in the notebook selection. This is a big user pain. It would be great to track the cause and find a remedy.

**Comment by sdradsb** [comment]
Thank you @emileten I will make the documentation clearer and look into point 2 as well.

**Comment by sdradsb** [comment]
@emileten here are the steps that I followed debugging point2 from this [comment](https://github.com/MAAP-Project/maap-documentation/issues/180#issuecomment-1544814008). 

- Installed `ipykernel` in the custom conda environment using: `conda install -c anaconda ipykernel`
- Registered the `ipykernel` using the command: `jupyter kernelspec uninstall tipython kernel install --name test --user`
- Verified kernel registration using the command: `jupyter kernelspec list`
- On refreshing the browser tab the kernel shows up instantly.

I couldn't find a delay between kernel registration and its availability in the notebook selection.

**Comment by sdradsb** [comment]
@emileten Is the [document](https://docs.maap-project.org/en/getting-started-pr-branch/system_reference_guide/custom-environments.html) you want me to change? 
And also , how do I edit this document? I have never done this before, apologies for the naive question.

**Comment by wildintellect** [comment]
@sdradsb make your proposed changes in https://github.com/MAAP-Project/maap-documentation/blob/Getting-Started-pr-branch/docs/source/system_reference_guide/custom-environments.ipynb (which is the source of the docs page you linked)

Reading over this, I would prefer if the original outlined solution was tested. There should be no need for any `kernelspec` commands. Only older versions of conda required that. Newer versions simply require that `ipykernel` or kernels for other langs (like R) be installed in the custom env. This is where the time delay comes in for the base environment to detect the new conda env.

**Comment by sdradsb** [comment]
@wildintellect Thank you, I will look into this.

**Comment by emileten** [comment]
Just to clarify @sdradsb, what I believe we essentially need is as a minimum improvement is, a modification to the `Using custom environments in jupyter notebooks` section of the docs you linked.

The modification needed is, somewhere in that section, highlight that the steps _must_ be executed in the following order for the kernel to show up on the notebook : 

```
1. create the conda environment with `ipykernel` in the dependencies listed in the configuration file, and activate the environment
2. run the kernel installation command
3. and then, open the notebook and select the kernel. 
```
The docs already provide this information but it's hidden in the text.

**Comment by sdradsb** [comment]
@wildintellect
I registered the ipykernel using the command: `python -m ipykernel install --user --name env3 --display-name "Python env3"` and on refreshing the browser tab the kernel still shows up instantly.

**Comment by wildintellect** [comment]
@sdradsb does it matter if that command is run in the (base) env or not?

**Comment by sdradsb** [comment]
@wildintellect I tried it in the base and custom env, and both worked.
