### ISSUE TITLE
Fix STAC API Docs url is api.html

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/maap-documentation#210]
@freitagb reported a typo in the docs about STAC, the Swagger API page explaining the api is wrong.

> Brian
> is this [“Not Found”](https://stac.maap-project.org/docs) expected?
> 
> Alex Mandel
> not sure I've never tried to hit docs endpoint on a STAC api
> let me go ask
> 
> Brian
> linked under bullet 2. [here](https://docs.maap-project.org/en/latest/technical_tutorials/search/catalog.html)
> 
> Alex Mandel
> right, I just noticed another deployment of STAC fastapi has the same issue
> typo in the docs, it's https://stac.maap-project.org/api.html which apparently is the OGC specs
> 
> Brian
> good find
> 
> Alex Mandel
> I asked Vincent (author on STAC fastapi)
> the confusion is that Titiler is /docs so easy to not realize the STAC api is different

**Comment by smk0033** [comment]
![image](https://github.com/MAAP-Project/maap-documentation/assets/124307788/9ad9ffc5-b737-4d33-8ff0-7705ca200cf9)

links that are set up like this also don't seem to work and go to a 404 Not Found error page. Do I need to put the whole path, or pull the link of the tutorial from the docs website?

**Comment by wildintellect** [comment]
@smk0033 that's a different issue for a different ticket (bigger issue to implement a link checker) but in this case the relative paths likely changed within the docs in the recent re-org.

**Comment by rtapella** [comment]
Yes that page was moved. Depending on where you are linking from it may just be a matter of going down a layer: technical_tutorials/search/…

**Comment by smk0033** [comment]
Completed
