### ISSUE TITLE
Update and Fix Broken Technical Tutorials

### ISSUE THREAD

**Issue by smk0033** [MAAP-Project/maap-documentation#230]
## Objective
[23.4 Obective 4:  Support MAAP Users in Achieving their Science Goals](https://github.com/NASA-IMPACT/active-maap-sprint/issues/667)

Related to:
#548 Remove Any Mentions of `CMR` and `search.maap-project.org` from `docs.maap-project.org`

## Description
While working on ticket [#548](https://github.com/orgs/NASA-IMPACT/projects/29/views/11?pane=issue&itemId=27143805), I realized some technical tutorials have other things that need to be updated and fixed for the tutorial to work. Will add the tutorials as needed, along with what needs to be updated.

## Acceptance Criteria (Tasks)
- [x] #231
- [x] #232
- [x] #233
- [x] #234
- [x] #235
- [x] #236
- [x] #237

Tutorials that were already updated and pushed in 23.3-4:
- accessing_gedi_l3_data
- accessing_gedi_l4a_data
- searching_compiling_list_of_granule_ids
- create-datasets-for-dashboard

**Comment by freitagb** [comment]
@sdradsb - please confirm the status of the tickets above for correctness.

**Comment by sdradsb** [comment]
Here are the updates to the tickets:
- [accessing_data](https://github.com/NASA-IMPACT/active-maap-sprint/issues/598)
- [interval_color_mapping](https://github.com/MAAP-Project/maap-documentation/issues/236)
- Ticket accessing_cod has some issues that needs to be addressed. Have commented on the ticket for advice.
- currently working on query_data_python and using_pycmc

**Comment by smk0033** [comment]
using_pycmc was moved to no status in the last sprint during one of our meetings - forgot the reason why, though

**Comment by smk0033** [comment]
PR for srtm-stac-mosaic: https://github.com/MAAP-Project/maap-documentation/pull/261

**Comment by wildintellect** [comment]
@smk0033 pycmc is currently not going to be ported to the NEW ADE, instead the docs will be converted to use stac_ipyleaflet.

**Comment by smk0033** [comment]
Closing - tutorials in EPIC have been fixed and query_data_python is being removed.
