### ISSUE TITLE
accessing_cod

### ISSUE THREAD

**Issue by smk0033** [MAAP-Project/maap-documentation#232]
## EPIC Link
#230 

## Acceptance Criteria (Tasks)
- [ ] Collection is not being pulled in (even when adding updated cmr_host and/or maap_host without .ops) - fix
- [x] fix broken links

**Comment by sdradsb** [comment]
Except for collection "FIFE_STRM_15M_1", all other collections have no granules in them. Even in the case "FIFE_STRM_15M_1" collection the URLs are pointing towards files with extension s15.

**Comment by sdradsb** [comment]
Link to PR: https://github.com/MAAP-Project/maap-documentation/pull/253
