### ISSUE TITLE
Confusion over installing conda packages from a yaml to an existing env

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/maap-documentation#251]
Creating a new Conda env from an env file is straight forward and well documented with https://docs.maap-project.org/en/develop/system_reference_guide/custom-environments.html#Basic-custom-environment

However https://docs.maap-project.org/en/develop/system_reference_guide/custom-environments.html#Extending-the-base-environment-in-a-given-workspace-session. Needs an additional section on how to update an existing env from a yaml defining packages. (Also remove the period on the heading)

Example:
```
mamba env update -n base --file above_env.yml
```
based on info from https://stackoverflow.com/questions/42352841/how-to-update-an-existing-conda-environment-with-a-yml-file

As reported by @pahbs in Slack on Jun 27, 2023.

**Comment by emileten** [comment]
@wildintellect we have that already https://docs.maap-project.org/en/latest/system_reference_guide/custom-environments.html#Updating-an-existing-environment-with-a-configuration-file

However the fact that you didn't find it means something is wrong. Sounds like it should go in https://docs.maap-project.org/en/latest/system_reference_guide/custom-environments.html#Extending-the-base-environment-in-a-given-workspace-session, but I had explicitly avoided mentioning configuration files in that first section, to leave the config files related topics to the next part.

**Comment by wildintellect** [comment]
I think it's easy to miss because it's in a paragraph. We should call it out in a code block with a title or caption.

**Comment by emileten** [comment]
addressed in https://github.com/MAAP-Project/maap-documentation/pull/252
