### ISSUE TITLE
Make it easier to copy code blocks

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/maap-documentation#256]
While reviewing ticket #252  we debated the best way for users to get examples of conda package yaml files.
I realized that a copy button on code blocks would be useful like many other online platforms have.
There is an extension for sphinx https://sphinx-copybutton.readthedocs.io/en/latest/ but I don't know what steps are required to make it work with ReadTheDocs

## Acceptance Criteria:
- [x] Determine a ReadTheDocs compatible method for adding a copy-button
- [x] Implement the feature

**Comment by rtapella** [comment]
example: https://docs.maap-project.org/en/code_copy_button/science/GEDI/GEDI_L2A.html
