### ISSUE TITLE
Align edav_wcs_data to VEDA notebook guidelines

### ISSUE THREAD

**Issue by smk0033** [MAAP-Project/maap-documentation#281]
## EPIC
#263 

## Description
The [edav_wcs_data](https://docs.maap-project.org/en/latest/technical_tutorials/access/edav_wcs_data.html) notebook should be reviewed using the this [guidance](https://nasa-impact.github.io/veda-docs/example-notebooks/#contributing-to-veda) and includes the following components:
1. Style
2. Rendering Information
3. Notebook Sections

### Acceptance Criteria (Tasks):

- [x] Style should be consistent with guidance provided
- [x] Rendering information should be complete and accurate
- [x] Ensure notebooks include the recommended standard sections

**Comment by smk0033** [comment]
Almost ready, updates are done but trying to run through the notebook and the link in the third cell is having trouble connecting

**Comment by smk0033** [comment]
Only placing in blocked for now because the link used for the tutorial (https://edav-wcs.adamplatform.eu/wcs) has not been working so far (says "This site can't be reached")

**Comment by wildintellect** [comment]
https://portal.val.esa-maap.org/portal-val/ESA/explore is the current EDAV front end. With some web-dev tools should be able to find the current WCS endpoint. Otherwise @freitagb can ask ESA for the updated url over email or in the next meeting on Sept 7.

**Comment by wildintellect** [comment]
New WCS url is likely https://edav-das.val.esa-maap.org/wcs

**Comment by smk0033** [comment]
PR: https://github.com/MAAP-Project/maap-documentation/pull/326
