### ISSUE TITLE
Align searching_compiling_list_of_granules to VEDA notebook guidelines

### ISSUE THREAD

**Issue by smk0033** [MAAP-Project/maap-documentation#286]
## EPIC
#263 

## Description
The [searching_compiling_list_of_granules](https://docs.maap-project.org/en/latest/technical_tutorials/search/searching_compiling_list_of_granule_ids.html) notebook should be reviewed using the this [guidance](https://nasa-impact.github.io/veda-docs/example-notebooks/#contributing-to-veda) and includes the following components:
1. Style
2. Rendering Information
3. Notebook Sections

### Acceptance Criteria (Tasks):

- [ ] Style should be consistent with guidance provided
- [ ] Rendering information should be complete and accurate. If there is no author/date information available, consult MAAP leads @wildintellect @abarciauskas-bgse for guidance
- [ ] Ensure notebooks include the recommended standard sections

**Comment by wildintellect** [comment]
@smk0033 can you add a link to the notebook referenced in the description above?

**Comment by smk0033** [comment]
PR: https://github.com/MAAP-Project/maap-documentation/pull/318
