### ISSUE TITLE
Align create-datasets-for-dashboard to VEDA notebook guidelines

### ISSUE THREAD

**Issue by smk0033** [MAAP-Project/maap-documentation#289]
## EPIC
#263 

## Description
The [create-datasets-for-dashboard](https://docs.maap-project.org/en/latest/technical_tutorials/user_data/create-datasets-for-dashboard.html) notebook should be reviewed using the this [guidance](https://nasa-impact.github.io/veda-docs/example-notebooks/#contributing-to-veda) and includes the following components:
1. Style
2. Rendering Information
3. Notebook Sections

### Acceptance Criteria (Tasks):

- [ ] Style should be consistent with guidance provided
- [ ] Rendering information should be complete and accurate. If there is no author/date information available, consult MAAP leads @wildintellect @abarciauskas-bgse for guidance
- [ ] Ensure notebooks include the recommended standard sections

**Comment by wildintellect** [comment]
@smk0033 
To get authors use, Git [Blame](https://github.com/MAAP-Project/maap-documentation/blame/develop/docs/source/technical_tutorials/user_data/create-datasets-for-dashboard.ipynb) and Git [History](https://github.com/MAAP-Project/maap-documentation/commits/96dc202c47c83f4b8523448ea8ed687078031e48/docs/source/user_data/create-datasets-for-dashboard.ipynb?browsing_rename_history=true&new_path=docs/source/technical_tutorials/user_data/create-datasets-for-dashboard.ipynb&original_branch=develop) as a first attempt  <- appears to be mostly written by Aimee originally
