### ISSUE TITLE
Align using_pycmc to VEDA notebook guidelines

### ISSUE THREAD

**Issue by smk0033** [MAAP-Project/maap-documentation#292]
## EPIC
#263 

## Description
The using_pycmc notebook should be reviewed using the this [guidance](https://nasa-impact.github.io/veda-docs/example-notebooks/#contributing-to-veda) and includes the following components:
1. Style
2. Rendering Information
3. Notebook Sections

### Acceptance Criteria (Tasks):

- [ ] Style should be consistent with guidance provided
- [ ] Rendering information should be complete and accurate. If there is no author/date information available, consult MAAP leads @wildintellect @abarciauskas-bgse for guidance
- [ ] Ensure notebooks include the recommended standard sections

**Comment by jjfrench** [comment]
I can't seem to find any information on this package 😅

**Comment by smk0033** [comment]
Removing tutorial
