### ISSUE TITLE
ReadTheDocs Build Changes

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/maap-documentation#298]
Some needs to look into this, and see what changes need to be made. I recall we had to change these setting maybe in #186 
Deadline is Aug 29th.

> 
> You are receving this email because your Read the Docs project is impacted by an upcoming deprecation.
> 
> Read the Docs used to pre-install common scientific Python packages like scipy, numpy, pandas, matplotlib and others at system level to speed up the build process. However, with all the work done in the Python ecosystem and the introduction of "wheels", these packages are a lot easier to install via pip install and these pre-installed packages are not required anymore. If you have Apt package dependencies, they can be installed with [build.apt_packages](https://docs.readthedocs.io/en/stable/config-file/v2.html#build-apt-packages).
> 
> With the introduction of our new "Ubuntu 20.04" and "Ubuntu 22.04" Docker images, we stopped pre-installing these extra Python packages and we encouraged users to install and pin all their dependencies using a requirements.txt file. We have already stopped supporting "use system packages" on these newer images.
> 
> We are removing the "use system packages" feature on August 29th. Make sure you are installing all the required dependecies to build your project's documentation using a requirements.txt file and specifying it in your .readthedocs.yaml.
> 
> Here you have an example of the section required on the .readthedocs.yaml configuration file:
> 
> python:
>   install:
>     - requirements: docs/requirements.txt
> 
> The content of docs/requirements.txt would be similar to:
> 
> scipy==1.11.1
> numpy==1.25.2
> pandas==2.0.3
> matplotlib==3.7.2
> 
> We are sending you this email because you are a maintainer of the following projects that are affected by this removal. Either using "Use system package" checkbox in the Admin UI, or the config key python.sytem_packages or python.use_system_site_packages in your .readthedocs.yaml file:
> 
>     [maap-project](https://readthedocs.org/projects/maap-project/)
> 
> Read more about this in our [Reproducible builds](https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html) guide for more details.
> Keep documenting,
> Read the Docs

**Comment by rtapella** [comment]
I think we already turned off the system packages. In the admin page: https://readthedocs.org/dashboard/maap-project/advanced/

<img width="690" alt="Screenshot 2023-08-14 at 10 11 05 AM" src="https://github.com/MAAP-Project/maap-documentation/assets/1156193/20399c42-a329-44e5-b881-46bae39c8985">

and in our `python.system_packages` in `.readthedocs.yml`

<img width="433" alt="Screenshot 2023-08-14 at 10 11 32 AM" src="https://github.com/MAAP-Project/maap-documentation/assets/1156193/0433a319-ab86-47d6-9141-ce910b17d372">

**Comment by rtapella** [comment]
(therefore I do not think we have any additional actions at this time. As far as I know we are installing everything we need via `requirements.txt`)

**Comment by wildintellect** [comment]
Ah, we are using the config key `system_packages: false` just happen to be setting it to false. So I agree this seems good to go, and a false positive on their detection because we are using the key but in a way that is compatible going forward.
