### ISSUE TITLE
Update ATL08 notebook

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/maap-documentation#33]
Update https://github.com/MAAP-Project/maap-documentation/blob/master/docs/source/query/testing-ept-stores.ipynb based on recent changes to https://github.com/MAAP-Project/maap-cumulus-dockers/blob/master/cumulus-point-cloud-tools/example-notebooks/testing-ept-stores.ipynb

**Comment by wildintellect** [comment]
@abarciauskas-bgse are you going to update this copy, or do you want me to do a PR?

**Comment by abarciauskas-bgse** [comment]
Hey @wildintellect sorry for the delayed response.

I think we want to update the notebook in read the docs but was wondering if we should wait until we deploy the features service as part of the MAAP API. I have a couple tickets for this in the trello board (currently under "D3 backlog" although I think probably Chuck and / or David Bitner have started to work on them). Given those trello tickets exist perhaps we can close this ticket?

**Comment by wildintellect** [comment]
This gets back to my notion that we need a docs staging area, with WIP aspects. Makes the lift to publish easier and keeps the docs together in once place. I agree this one can now wait until we update the deploy early next week, but we should at least put the draft in, and update later once rolled into the MAAP API. If we don't clearly document it in current state UWG can't be pointed to it easily.

**Comment by abarciauskas-bgse** [comment]
closing as stle
