### ISSUE TITLE
Document DPS configuration options

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/maap-documentation#336]
Users are confused about what options are available in algorithm configuration and what that implies for how and algorithm main shell script is then written. e.g. File(s) vs inputs

Likely location
https://docs.maap-project.org/en/latest/getting_started/running_at_scale.html#Register-an-Algorithm
but could be a new page under technical tutorials.

## Acceptance Criteria
- [ ] Algorithm Configuration options
- [ ] How to use input/reference variables in shell scripts (DPS jobs)

See also #278 #274

**Comment by rtapella** [comment]
migrated to https://github.com/MAAP-Project/maap-documentation/issues/400

**Comment by rtapella** [comment]
added to #400
