### ISSUE TITLE
Mention the `triaged-jobs` folder in DPS related documentation

### ISSUE THREAD

**Issue by emileten** [MAAP-Project/maap-documentation#349]
I've been testing the DPS for the first time this week, and before Jamison showed me the `triaged-jobs` folder in the ADE workspace, the only thing I was relying on to see what the errors of my jobs were resulting from was the job viewer UI, and what's displayed is insufficient. This `triaged-jobs` folder that contains full logs was key to understand my failures, but it is not mentioned at all in the docs. Besides, it seems that it is not by default accessible in all workspaces types (It is in the vanilla one, but not in the pangeo one for example).

- [ ] mention the `triaged-jobs` folder in the DPS docs
- [ ] explain how to access it if it's not present in a workspace.It's an S3 bucket mount, so one can add to a workspace devfile that mount.

**Comment by rtapella** [comment]
@grallewellyn is this done?

**Comment by grallewellyn** [comment]
Yes: https://github.com/MAAP-Project/maap-documentation/pull/404

**Comment by rtapella** [comment]
https://github.com/MAAP-Project/Community/issues/968
