### ISSUE TITLE
HLS science tutorial is blank

### ISSUE THREAD

**Issue by rtapella** [MAAP-Project/maap-documentation#443]
https://docs.maap-project.org/en/latest/science/HLS/HLSL30.html

- the page comes up blank
- a local build does not have the same issue

**Comment by wildintellect** [comment]
We've narrowed it down. Known bug with the new Add-ons feature of ReadTheDocs and large files. This particular notebook being over 20 MB.

>"So far, two solutions are to output image files instead of inlining the images, or you might be able to disable Addons temporarily"

- https://stackoverflow.com/questions/79091590/read-the-docs-build-has-blank-html-for-some-pages
- https://matrix.to/#/!LVjngZMcDVmwNVkCqi:gitter.im/$KFeb_LmW1CW-UlJhy5EaiBlRL6jclHZ0SPbxRy4pIpc?via=gitter.im&via=matrix.org&via=cadair.com

We're looking into compressing images within the notebook. Looking at alternate methods to export the figures to individual files with separate compression and link them in via Markdown, not actual cell output which should shrink the file size.
