### ISSUE TITLE
Update notebooks to point at titiler-pgstac.maap-project.org instead of titiler.maap-project.org

### ISSUE THREAD

**Issue by hrodmn** [MAAP-Project/maap-documentation#451]
In pursuit of a single consolidated titiler deployment for MAAP:

- [x] [docs/source/technical_tutorials/visualization/stac_ipyleaflet.ipynb](https://github.com/MAAP-Project/maap-documentation/blob/964d8d583a021e8c9825d5baaf4ea8fdad02dc10/docs/source/technical_tutorials/visualization/stac_ipyleaflet.ipynb#L204)
- [x] [docs/source/technical_tutorials/user_data/create-datasets-for-dashboard.ipynb](https://github.com/MAAP-Project/maap-documentation/blob/964d8d583a021e8c9825d5baaf4ea8fdad02dc10/docs/source/technical_tutorials/user_data/create-datasets-for-dashboard.ipynb#L112)
- [x] [docs/source/technical_tutorials/visualization/visualize_mosaic_stac_ipyleaflet.ipynb](https://github.com/MAAP-Project/maap-documentation/blob/964d8d583a021e8c9825d5baaf4ea8fdad02dc10/docs/source/technical_tutorials/visualization/visualize_mosaic_stac_ipyleaflet.ipynb#L35)
- [x] [docs/source/technical_tutorials/visualization/interval_color_mapping.ipynb](https://github.com/MAAP-Project/maap-documentation/blob/964d8d583a021e8c9825d5baaf4ea8fdad02dc10/docs/source/technical_tutorials/visualization/interval_color_mapping.ipynb#L125)

**Comment by wildintellect** [comment]
@hrodmn if we're merging the functionality, then don't we just need to deploy titiler-pgstac to the original titiler.maap-project.org and call it done?

**Comment by hrodmn** [comment]
> [@hrodmn](https://github.com/hrodmn) if we're merging the functionality, then don't we just need to deploy titiler-pgstac to the original titiler.maap-project.org and call it done?

`titiler-pgstac.maap-project.org` has all* of the endpoints that we supported at the `titiler.maap-project.org` deployment, so in theory we could just flip a switch and point all `titiler.maap-project.org` to the `titiler-pgstac` Lambda.
    \* /cog/crop -> /cog/bbox

I suppose we can pick whatever url we want to stick with long-term and associate it with the titiler-pgstac deployment. I can see advantages/disadvantages to either url:

**titiler.maap-project.org**:
- advantages
  - users do not need to update urls in notebooks
- disadvantages
  - once we flip the switch it could break functionality for a few limited use-cases 

**titiler-pgstac.maap-project.org**:
- advantages
  - keeping the new domain would allow us to add some deprecation warnings to responses in `titiler.maap-project.org` endpoints
    - enables a "phaseout" period for `titiler.maap-project.org`
  - no changes required to domain name infrastructure, just need to tear down `titiler.maap-project.org` at some point
- disadvantages
  - somewhat clunky domain name
  - adding a "phaseout period" where we maintain both APIs but add deprecation warnings might be more trouble than it is worth

**Comment by wildintellect** [comment]
Decided to not do this until we know what domain we want to use.
