### ISSUE TITLE
Warning message displayed after signing in immediately following registration

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/maap-documentation#70]
Earlier today I registered for an account on [pilot ops](http://maap-project.org/) and [gcc ops](http://ops.maap-project.org/). After successfully registering for an account in both environments, I tried to sign in and encountered a warning message as shown below.  After a few minutes passed, I was able to sign in successfully. These errors could be confusing for new users when one considers that the response provided to users after registration stated something along the lines of their account being created and activated.

##### Pilot OPS:

<img width="1280" alt="Screen Shot 2021-06-28 at 12 55 20" src="https://user-images.githubusercontent.com/931107/123707588-c8896c80-d81e-11eb-9bbc-1a2e4da61fee.png">

##### GCC OPS:

<img width="1280" alt="Screen Shot 2021-06-28 at 13 25 43" src="https://user-images.githubusercontent.com/931107/123707602-cfb07a80-d81e-11eb-9561-1cd52e29cc1d.png">

**Comment by abarciauskas-bgse** [comment]
closing as stale
