### ISSUE TITLE
ADE technical documentation references removed

### ISSUE THREAD

**Issue by marjo-luc** [MAAP-Project/maap-documentation#80]
@spa0002 it looks like [this commit](https://github.com/MAAP-Project/maap-documentation/commit/3105c3f0c0f6bab41780a13a7ec36b86b726851e) removed the references to the ADE technical documentation. Was this intentional? If so, could you provide justification? If not, could I make the updates to the doctree to get them back in?

**Comment by spa0002** [comment]
Not intended. I noticed this a little while ago and I am making edits to
add them to toc, updating image links

**Comment by spa0002** [comment]
https://github.com/MAAP-Project/maap-documentation/pull/81

**Comment by marjo-luc** [comment]
Resolved
